// 1. ROLES
export const ROLES = {
  SUPER_ADMIN: 'super_admin',
  ADMIN: 'admin',
  INVENTORY_MANAGER: 'inventory_manager',
  ACQUISITIONS_MANAGER: 'acquisitions_manager',
  ARTICLES_MANAGER: 'articles_manager',
  APPOINTMENTS_MANAGER: 'appointments_manager',
  VIEWER: 'viewer',
};

// Higher number = Higher power
export const ROLE_HIERARCHY = {
  [ROLES.SUPER_ADMIN]: 100,
  [ROLES.ADMIN]: 90,

  // Managers are peers (Level 50)
  [ROLES.INVENTORY_MANAGER]: 50,
  [ROLES.ACQUISITIONS_MANAGER]: 50,
  [ROLES.ARTICLES_MANAGER]: 50,
  [ROLES.APPOINTMENTS_MANAGER]: 50,

  [ROLES.VIEWER]: 10,
};

// 2. PERMISSIONS (CRUD SETUP)
export const PERMISSIONS = {
  VIEW_DASHBOARD: 'view_dashboard',
  VIEW_ADMIN_TOOLS: 'view_admin_tools',
  VIEW_SOCKET_TEST: 'view_socket_test',
  MANAGE_TRASH: 'manage_trash',

  CREATE_USERS: 'create_users',
  READ_USERS: 'read_users',
  UPDATE_USERS: 'update_users',
  DELETE_USERS: 'delete_users',
  MANAGE_USER_ROLES: 'manage_user_roles',
  MANAGE_USER_STATUS: 'manage_user_status',
  DISCONNECT_USERS: 'disconnect_users',

  CREATE_DONATIONS: 'create_donations',
  READ_DONATIONS: 'read_donations',
  UPDATE_DONATIONS: 'update_donations',
  DELETE_DONATIONS: 'delete_donations',

  CREATE_INVENTORY: 'create_inventory',
  READ_INVENTORY: 'read_inventory',
  UPDATE_INVENTORY: 'update_inventory',
  DELETE_INVENTORY: 'delete_inventory',

  CREATE_ARTICLES: 'create_articles',
  READ_ARTICLES: 'read_articles',
  UPDATE_ARTICLES: 'update_articles',
  DELETE_ARTICLES: 'delete_articles',

  CREATE_ACQUISITIONS: 'create_acquisitions',
  READ_ACQUISITIONS: 'read_acquisitions',
  UPDATE_ACQUISITIONS: 'update_acquisitions',
  DELETE_ACQUISITIONS: 'delete_acquisitions',

  CREATE_APPOINTMENTS: 'create_appointments',
  READ_APPOINTMENTS: 'read_appointments',
  UPDATE_APPOINTMENTS: 'update_appointments',
  DELETE_APPOINTMENTS: 'delete_appointments',

  READ_AUDIT_LOGS: 'read_audit_logs',

  READ_TRASH: 'read_trash',
  RESTORE_TRASH: 'restore_trash',
  DELETE_TRASH: 'delete_trash',
};

export const ROLE_DEFINITIONS = {
  [ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS),
  [ROLES.ADMIN]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_ADMIN_TOOLS,
    PERMISSIONS.VIEW_SOCKET_TEST,
    PERMISSIONS.READ_AUDIT_LOGS,
    PERMISSIONS.CREATE_USERS,
    PERMISSIONS.READ_USERS,
    PERMISSIONS.UPDATE_USERS,
    PERMISSIONS.MANAGE_USER_STATUS,
    PERMISSIONS.DISCONNECT_USERS,
    PERMISSIONS.READ_DONATIONS,
    PERMISSIONS.UPDATE_DONATIONS,
    PERMISSIONS.READ_INVENTORY,
    PERMISSIONS.UPDATE_INVENTORY,
    PERMISSIONS.READ_ARTICLES,
    PERMISSIONS.UPDATE_ARTICLES,
    PERMISSIONS.DELETE_ARTICLES,
    PERMISSIONS.READ_APPOINTMENTS,
    PERMISSIONS.UPDATE_APPOINTMENTS,
    PERMISSIONS.READ_ACQUISITIONS,
    PERMISSIONS.READ_AUDIT_LOGS
  ],
  [ROLES.INVENTORY_MANAGER]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.READ_DONATIONS,
    PERMISSIONS.UPDATE_DONATIONS,
    PERMISSIONS.CREATE_INVENTORY,
    PERMISSIONS.READ_INVENTORY,
    PERMISSIONS.UPDATE_INVENTORY,
    PERMISSIONS.DELETE_INVENTORY,
  ],
  [ROLES.ACQUISITIONS_MANAGER]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.READ_ACQUISITIONS,
    PERMISSIONS.CREATE_ACQUISITIONS,
    PERMISSIONS.UPDATE_ACQUISITIONS,
    PERMISSIONS.READ_DONATIONS,
  ],
  [ROLES.ARTICLES_MANAGER]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.CREATE_ARTICLES,
    PERMISSIONS.READ_ARTICLES,
    PERMISSIONS.UPDATE_ARTICLES,
    PERMISSIONS.DELETE_ARTICLES,
  ],
  [ROLES.APPOINTMENTS_MANAGER]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.READ_APPOINTMENTS,
    PERMISSIONS.UPDATE_APPOINTMENTS,
    PERMISSIONS.READ_USERS,
  ],
  [ROLES.VIEWER]: [PERMISSIONS.VIEW_DASHBOARD, PERMISSIONS.READ_ARTICLES],
};

export const getAllowedRoles = () => Object.values(ROLES);
